<?php

namespace App\Providers;

use App\Repositories\Read\Payment\PaymentReadRepository;
use App\Repositories\Read\Payment\PaymentReadRepositoryInterface;
use App\Repositories\Read\User\UserReadRepository;
use App\Repositories\Read\User\UserReadRepositoryInterface;
use App\Repositories\Write\Payment\PaymentWriteRepository;
use App\Repositories\Write\Payment\PaymentWriteRepositoryInterface;
use App\Repositories\Write\PaymentWebhook\PaymentWebhookWriteRepository;
use App\Repositories\Write\PaymentWebhook\PaymentWebhookWriteRepositoryInterface;
use App\Repositories\Write\User\UserWriteRepository;
use App\Repositories\Write\User\UserWriteRepositoryInterface;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

class RepositoryServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->app->bind(
            UserWriteRepositoryInterface::class,
            UserWriteRepository::class,
        );

        $this->app->bind(
            UserReadRepositoryInterface::class,
            UserReadRepository::class,
        );

        $this->app->bind(
            PaymentReadRepositoryInterface::class,
            PaymentReadRepository::class,
        );

        $this->app->bind(
            PaymentWriteRepositoryInterface::class,
            PaymentWriteRepository::class,
        );

        $this->app->bind(
            PaymentWebhookWriteRepositoryInterface::class,
            PaymentWebhookWriteRepository::class,
        );
    }

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
